#!/usr/bin/env python2
from pwn import *
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-q', '--quite', dest='quite', help='shut pwntools up', action='store_true')
    parser.add_argument('-r', '--remote', dest='remote', help='run on remote', action='store_true')
    parser.add_argument('-g', '--gdb', dest='gdb', help='attach to gdb', action='store_true')
    return parser.parse_args()
args=parse_args()

context.log_level='DEBUG' if not args.quite else 'WARN'
context.terminal=['/usr/bin/termite', '-e']

binary=''

e=ELF(binary)

if not args.remote:
    p=process(binary)
    if args.gdb:
        gdb.attach(p)
else:
    p=remote('', 0)

def solve():
    pass

solve()
p.interactive()
